"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
secret_key = os.environ.get('SECRET_KEY')
debug_mode = os.environ.get('DEBUG')
allowed_host = os.environ.get('ALLOWED_HOSTS')
cors_allowed_origins=os.environ.get('CORS_ALLOWED_ORIGINS')

# Mongo
# mongo_db_name = os.environ.get('MONGO_DATABASE_NAME')
# mongo_host = os.environ.get('MONGO_HOST')
# mongo_port = os.environ.get('MONGO_PORT')
# mongo_user = os.environ.get('MONGO_USER')
# mongo_password = os.environ.get('MONGO_PASSWORD')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = debug_mode

ALLOWED_HOSTS = [allowed_host]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'main.apps.conversation_mgt',
    'main.apps.workflow_mgt',
    'main.apps.topic_mgt',
    'main.apps.metadata_mgt',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_allowed_origins.split(',') if origin.strip()]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'main.asgi.application'
#WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('HTTP_POSTGRES_DATABASE_NAME'),
        'USER': os.environ.get('HTTP_POSTGRES_DATABASE_HOST_USER'),
        'PASSWORD': os.environ.get('HTTP_POSTGRES_DATABASE_PASSWORD'),
        'HOST': os.environ.get('HTTP_POSTGRES_DATABASE_HOST'),
        'PORT': os.environ.get('HTTP_POSTGRES_DATABASE_HOST_PORT')
    },
}

REDIS_USER = os.getenv("HTTP_REDIS_DATABASE_HOST_USER", "")
REDIS_PASSWORD = os.getenv("HTTP_REDIS_DATABASE_PASSWORD", "")
REDIS_HOST = os.getenv("HTTP_REDIS_DATABASE_HOST", "")
REDIS_PORT = os.getenv("HTTP_REDIS_DATABASE_HOST_PORT", "6379")
REDIS_DB   = os.getenv("HTTP_REDIS_DATABASE_INDEX", "1")

REDIS_URI = f"redis://{REDIS_USER}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URI],
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# BASE_DIR 現在正確指向了 'ITRI-Intent-Based-SMO'
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# 定義媒體檔案的 URL 前綴，前端將通過這個 URL 訪問媒體檔案
MEDIA_URL = '/media/'

# 定義媒體檔案在伺服器上的實際儲存路徑
# 這會將檔案儲存在你的專案根目錄下的 'media' 資料夾中
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')