# Generated by Django 4.2 on 2025-01-24 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_role', models.CharField(blank=True, max_length=50, null=True)),
                ('user_email', models.CharField(max_length=255, unique=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('conversation_path', models.CharField(max_length=255)),
                ('conversation_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('f_user_uid', models.ForeignKey(db_column='f_user_uid', on_delete=django.db.models.deletion.CASCADE, to='metadata_mgt.user', to_field='user_uid')),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
    ]
