# Generated by Django 4.2 on 2025-02-03 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('text_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('f_conversation_uid', models.ForeignKey(db_column='f_conversation_uid', on_delete=django.db.models.deletion.CASCADE, to='metadata_mgt.conversation', to_field='conversation_uid')),
                ('f_user_uid', models.ForeignKey(db_column='f_user_uid', on_delete=django.db.models.deletion.CASCADE, to='metadata_mgt.user', to_field='user_uid')),
            ],
            options={
                'db_table': 'text',
            },
        ),
    ]
