# Generated by Django 4.2 on 2025-02-05 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_mgt', '0002_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_step', models.CharField(max_length=50)),
                ('workflow_status', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('f_conversation_uid', models.OneToOneField(db_column='f_conversation_uid', on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='metadata_mgt.conversation', to_field='conversation_uid')),
            ],
            options={
                'db_table': 'workflow',
            },
        ),
    ]
