# Generated by Django 4.2 on 2025-02-18 05:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_mgt', '0003_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFlow',
            fields=[
                ('api_flow_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_flow_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('api_flow_name', models.CharField(max_length=255)),
                ('api_flow_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_flow',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scenario_name', models.CharField(max_length=255)),
                ('scenario_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scenario',
            },
        ),
        migrations.CreateModel(
            name='ApiFlowStep',
            fields=[
                ('api_flow_step_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_flow_step_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('api_flow_step_name', models.CharField(max_length=255)),
                ('api_flow_step_description', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('field', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('f_api_flow_uid', models.ForeignKey(db_column='f_api_flow_uid', on_delete=django.db.models.deletion.CASCADE, related_name='api_flow_steps', to='metadata_mgt.apiflow', to_field='api_flow_uid')),
            ],
            options={
                'db_table': 'api_flow_step',
            },
        ),
        migrations.AddField(
            model_name='apiflow',
            name='f_scenario_uid',
            field=models.ForeignKey(db_column='f_scenario_uid', on_delete=django.db.models.deletion.CASCADE, related_name='api_flows', to='metadata_mgt.scenario', to_field='scenario_uid'),
        ),
    ]
