# Generated by Django 3.1.12 on 2025-02-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_mgt', '0004_apiflow_scenario_apiflowstep_apiflow_f_scenario_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiflowstep',
            name='api_flow_step_ready',
            field=models.BooleanField(default=False, help_text='所有欄位都ready時，設為True'),
        ),
    ]
