# Generated by Django 4.2 on 2025-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_mgt', '0005_apiflowstep_api_flow_step_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiflowstep',
            name='f_api_flow_uid',
        ),
        migrations.AddField(
            model_name='conversation',
            name='dify_conversation_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='ApiFlow',
        ),
        migrations.DeleteModel(
            name='ApiFlowStep',
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
    ]
