# Generated by Django 4.2 on 2025-07-03 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_mgt', '0006_remove_apiflowstep_f_api_flow_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('f_conversation_uid', models.ForeignKey(db_column='f_conversation_uid', on_delete=django.db.models.deletion.CASCADE, to='metadata_mgt.conversation', to_field='conversation_uid')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
