# Generated by Django 4.2 on 2025-07-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_mgt', '0007_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='user_uemail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='user_uname',
        ),
    ]
