# Generated by Django 4.2 on 2025-11-28 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_mgt', '0008_rename_user_email_user_user_uemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('agent_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_key', models.CharField(max_length=255)),
                ('f_user_uid', models.ForeignKey(db_column='f_user_uid', on_delete=django.db.models.deletion.CASCADE, to='metadata_mgt.user', to_field='user_uid')),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='f_agent_uid',
            field=models.ForeignKey(db_column='f_agent_uid', default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, to='metadata_mgt.agent', to_field='agent_uid'),
        ),
    ]
